
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: ea-glog-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/gottingen/glog
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: A copy of glog

source:
  git_url: ../

outputs:
  - name: ea-glog
    script: bld.sh   # [not win]
    script: bld.bat  # [win]
    build:
      string: "h{{ GIT_DESCRIBE_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('glog', exact=True) }}
    requirements:
      build:
        - ea-gflags >=2.2.2
      host:
        - ea-gflags >=2.2.2
      run:
        - ea-gflags >=2.2.2
    test:
      commands:
        - test -f $PREFIX/lib/libglog.so              # [linux]
        - test -f $PREFIX/lib/libglog.dylib           # [osx]
      #  - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
      #  - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
